export const loginLocalization = {
  loginToAccount: 'ورود به حساب کاربری',
  email: 'ایمیل',
  password: 'رمز عبور',
  fogetPassword: 'فراموشی رمز عبور',
  login: 'ورود',
  loginWithOther: 'ورود با حساب گوگل',
  doYouWantAccount: 'آیا قبلا حساب کاربری نداشتید؟',
  signUp: 'ساخت حساب کاربری',
  shine: 'درخشش بی پایان',
  text1: 'با هر قطعه ای که انتخاب میکنید،داستانی از',
  text2: 'شکوه و زیبایی را روایت کنید.',
  text3:"جواهرات و اکسسوری هایی که درخشش شما را",
  text4:"جاودانه می کنند.",
};