export const loginLocalization = {
  loginToAccount: 'ورود به حساب کاربری',
  email: 'ایمیل',
  password: 'رمز عبور',
  fogetPassword: 'فراموشی رمز عبور',
  login: 'ورود',
  loginWithOther: 'ورود با حساب گوگل',
  doYouWantAccount: 'آیا قبلا حساب کاربری نداشتید؟',
  signUp: 'ساخت حساب کاربری',
  shine: 'درخشش بی پایان',
  text1: 'با هر قطعه ای که انتخاب میکنید،داستانی از',
  text2: 'شکوه و زیبایی را روایت کنید.',
  text3: 'جواهرات و اکسسوری هایی که درخشش شما را',
  text4: 'جاودانه می کنند.',
  usernamevalidate:' نام کاربری بین 3 تا 20 کارکتر و ترکیبی از حروف انگلیسی باشد ',
  usernameriquired: 'نام کاربری الزامی است',
  passwordriquired: 'رمز عبور اجباری است',
  passwordvalidate: 'رمز عبور دارای 8 کارکتر و ترکیبی از اعداد و حروف باشد',
  toastsuccess:'✅ ورود با موفقیت انجام شد',
  toasrerror:'❌ ورود موفقیت امیز نبود'
};