import { Metadata } from 'next';
import './globals.css';


export const metadata: Metadata = {
  title: 'aika gallery',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir='rtl' lang="fa">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
