import AdHeader from '@/components/Layout/AdHeader/AdHeader';
import { Metadata } from 'next';
import './globals.css'
import Sidebar from '@/components/AdPanel/Sidebar/Sidebar';
import ProtectedRoute from '@/components/PrivateRoute/PrivateRoute';

export const metadata: Metadata = {
  title: 'aika admin',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html dir="rtl" lang="fa">
      <body className="grid grid-cols-[10%,90%] bg-custom-50">
        <ProtectedRoute>
          <div>
            <Sidebar />
          </div>
          <div>
            <AdHeader />
            <main className="flex-grow pl-4 -pt-4">{children}</main>
          </div>
        </ProtectedRoute>
      </body>
    </html>
  );
}
