import AdFooter from '@/components/Layout/AdFooter/AdFooter';
import AdHeader from '@/components/Layout/AdHeader/AdHeader';
import { Metadata } from 'next';
import './globals.css'
import Sidebar from '@/components/AdPanel/Sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'aika admin',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html dir="rtl" lang="fa">
      <body className="grid grid-cols-[10%,90%]">
        <div>
          <Sidebar/>
        </div>
        <div>
          <AdHeader />
          <main className="flex-grow pl-4 -pt-4">{children}</main>
          <AdFooter />
        </div>
      </body>
    </html>
  );
}
