import AdFooter from '@/components/Layout/AdFooter/AdFooter';
import AdHeader from '@/components/Layout/AdHeader/AdHeader';
import { Metadata } from 'next';
import './globals.css'

export const metadata: Metadata = {
  title: 'aika admin',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir='rtl' lang="fa">
      <body className="min-h-screen flex flex-col">
        <AdHeader />
        <main className="flex-grow p-4">{children}</main>
        <AdFooter />
      </body>
    </html>
  );
}
