import WebFooter from '@/components/Layout/WebFooter/WebFooter';
import WebHeader from '@/components/Layout/WebHeader/WebHeader';
import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'aika gallery',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir='rtl' lang="fa">
      <body className="min-h-screen flex flex-col">
        <WebHeader />
        <main className="flex-grow p-4">{children}</main>
        <WebFooter />
      </body>
    </html>
  );
}
