import WebFooter from '@/components/Layout/WebFooter/WebFooter';
import WebHeader from '@/components/Layout/WebHeader/WebHeader';
import { Metadata } from 'next';
import './globals.css'
import 'leaflet/dist/leaflet.css';
import CartDrawer from '@/components/Cart/CartDrawer/CartDrawer';
import ReduxProvider from '@/components/redux/provider';

export const metadata: Metadata = {
  title: 'aika gallery',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="fa">
      <body className="min-h-screen">
        <ReduxProvider>
          <CartDrawer />
          <WebHeader />
          <main>{children}</main>
          <WebFooter />
        </ReduxProvider>
      </body>
    </html>
  );
}